// Generated by CoffeeScript 1.7.1
(function() {
  var cheerio, util, _parseDaily, _parseQuestion, _parseQuestionContent, _parseTopic, _parseTopicContent;

  util = require("./util");

  cheerio = require("cheerio");


  /*
      zhihu parser
      @param {String} url
      @param {Function} cb callback function
   */

  exports.parse = function(url, cb) {
    if (url) {
      if (util.isZhihuDaily(url)) {
        return _parseDaily(url, cb);
      } else if (util.isZhihuQuestion(url)) {
        return _parseQuestion(url, cb);
      } else if (util.isZhihuTopic(url)) {
        return _parseTopic(url, cb);
      } else {
        return cb(new Error("url " + url + " isn't zhihu daily or zhihu question"));
      }
    } else {
      return cb(new Error("must have a url"));
    }
  };


  /*
      parse zhihu tags
      @param {String} url
      @param {Function} cb callback function
   */

  _parseTopic = function(url, cb) {
    return util.download(url, function(err, content) {
      var $, topic;
      if (err) {
        return cb(err);
      }
      $ = cheerio.load(content);
      topic = _parseTopicContent(err, content, $);
      return cb(null, topic);
    });
  };

  exports.parseTopicContent = _parseTopicContent = function(err, content, $) {
    var followerCount, questionsArr, tagsArr, title, topic;
    if (err) {
      return err;
    }
    title = util.getTopicTitle($('#zh-topic-title'));
    followerCount = util.getFollowerCount($('#zh-topic-side-head'));
    tagsArr = util.getTags($, $("#zh-topic-side-children-list .zm-item-tag"));
    questionsArr = util.getTopicQuestions($, $('.question_link'));
    return topic = {
      title: title,
      followerCount: followerCount,
      questions: questionsArr,
      childTags: tagsArr
    };
  };


  /*
      parse zhihu question
      @param {String} url
      @param {Function} cb callback function
   */

  _parseQuestion = function(url, cb) {
    return util.download(url, function(err, content) {
      var $, article;
      if (err) {
        return cb(err);
      }
      $ = cheerio.load(content);
      article = _parseQuestionContent(err, content, $);
      return cb(null, article);
    });
  };

  exports.parseQuestionContent = _parseQuestionContent = function(err, content, $) {
    var answers, answersArr, article, followerCount, question, tagElems, tags, title;
    if (err) {
      return err;
    }
    title = $('#zh-question-title').text().trim();
    followerCount = util.getFollowerCount($('#zh-question-side-header-wrap'));
    question = $("#zh-question-detail").html().trim();
    tagElems = $(".zm-item-tag");
    tags = [];
    tagElems.each(function(i, el) {
      return tags.push($(el).text().trim());
    });
    answersArr = [];
    answers = $('.zm-item-answer');
    answers.each(function() {
      var answerDetail, authorInfo, node;
      node = $(this);
      authorInfo = node.find('.zm-item-answer-author-wrap').text().trim();
      node.find('.toggle-expand').remove();
      answerDetail = node.find('.zm-editable-content');
      util.pullOutRealPath(answerDetail);
      util.trimAttrs(answerDetail);
      return answersArr.push({
        author: util.getAuthor(authorInfo),
        content: answerDetail.html().trim()
      });
    });
    return article = {
      title: title,
      followerCount: followerCount,
      question: question,
      tags: tags,
      answers: answersArr
    };
  };


  /*
      parse zhihu daily page
      @param {String} url
      @param {Function} cb callback function
   */

  _parseDaily = function(url, cb) {
    return util.download(url, function(err, content) {
      var $, answers, answersArr, article, imgSrc, question, title;
      if (err) {
        return cb(err);
      }
      $ = cheerio.load(content);
      title = $('title').text();
      imgSrc = $('.img-wrap img').attr('src').trim();
      question = $('.question-title').text();
      answers = $('.answer');
      answersArr = [];
      answers.each(function() {
        var answerDetail, author, node;
        node = $(this);
        author = node.find('.meta').text();
        answerDetail = node.find('.content');
        util.pullOutRealPath(answerDetail);
        util.trimAttrs(answerDetail);
        return answersArr.push({
          author: util.getAuthor(author.trim()),
          content: answerDetail.html().trim()
        });
      });
      article = {
        title: title,
        question: question,
        image: imgSrc,
        answers: answersArr
      };
      return cb(null, article);
    });
  };

}).call(this);

//# sourceMappingURL=index.map
